### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by fxn9801** [dlyt/react-koa-login#2]
运行npm dev 报如下错误是为什么呢？
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\studySpace\re
act-koa-login\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:/studySpace/react-koa-login/bin/server.js:8:1)
    at Module._compile (module.js:570:32)
    at loader (D:\studySpace\react-koa-login\node_modules\babel-register\lib\nod
e.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\studySpace\re
act-koa-login\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by dlyt** [comment]
koa-mount换成2.0
我已经改了，你可以重新拉一下代码。
